blank_issues_enabled: true
contact_links:
  - name: Zenium Core Security Policy
    url: https://github.com/zenium-community/zenium/blob/master/SECURITY.md
    about: View security policy
  - name: Zenium Core Developers
    url: https://zenium.org
    about: Zenium Core homepage
