.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. zenium_qt test_zenium_qt
clean: FORCE
	$(MAKE) -C .. zenium_qt_clean test_zenium_qt_clean
check: FORCE
	$(MAKE) -C .. test_zenium_qt_check
zenium-qt zenium-qt.exe: FORCE
	 $(MAKE) -C .. zenium_qt
apk: FORCE
	$(MAKE) -C .. zenium_qt_apk
